### ISSUE TITLE
Support for H5179

### ISSUE THREAD

**Issue by V1irus** [vnau/FritzGate#4]
Hi, just got an H5179 + EPS32CAM. 
Unfortunately I miss took 

> integrating third-party temperature sensors _**like**_ Govee H5075 

as **_many_** more. So Are there any plans for Supporting any other Sensors? 

Cheers

**Comment by vnau** [comment]
Hi, @V1irus,

the description may actually be a bit confusing. There were plans to implement support for other Govee sensors.

It should be pretty easy to add support for the H5179, as its protocol is quite similar to the H5075. Unfortunately, don't have the H5179 sensor myself and can't test whether it will work properly.

**Comment by V1irus** [comment]
Right, I tried to modify to support any other Sensor. But no cake. Seems like I'm looking in the wrong direction 


Cheers

**Comment by vnau** [comment]
@V1irus Hopefully added support for H5179.

I just checked it on a test sequence, would appreciate if you can test it on a real device and confirm if it works correctly.

**Comment by V1irus** [comment]
Well seems a bit of :D 

![image](https://github.com/vnau/FritzGate/assets/23128139/2d92d711-aca6-419e-92c6-0725bb3e0747)
![image](https://github.com/vnau/FritzGate/assets/23128139/d0ab67ec-cfd2-4cbc-97ad-60d63f48405c)

**Comment by vnau** [comment]
FritzGate now utilizes the Theengs Decoder, supporting [70+ sensor models](https://decoder.theengs.io/devices/devices.html), including the Govee H5179, so I'm closing the issue.
